- name: Verify registration using valid input
  hosts: caixa_demo
  become: true
  gather_facts: false
  pre_tasks:
    - ansible.builtin.import_tasks: tasks/guard.yml
  tasks:
    - ansible.builtin.import_tasks: tasks/verify.yml
